version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: sauu_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sauu
      POSTGRES_PASSWORD: sauu_dev_password
      POSTGRES_DB: sauu_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
